name: stackvm_tool
description: Automation tool for benchmarks
version: 1.0.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  crypto: ^3.0.1
  yaml_edit: ^2.0.1
  yaml: any
  csv: any

dev_dependencies:
  pedantic: ^1.9.0
